export default [
  {
    label: 'React',
    icon: 'react',
    value: 'react',
    color: '61DAFB',
  },
  {
    label: 'Vue',
    icon: 'vuedotjs',
    value: 'vue',
    color: '4FC08D',
  },
  {
    label: 'Angular',
    icon: 'angular',
    value: 'angular',
    color: '0F0F11',
  },
  {
    label: 'Solid',
    icon: 'solid',
    value: 'solid',
    color: '2C4F7C',
  },
  {
    label: 'Svelte',
    icon: 'svelte',
    value: 'svelte',
    color: 'FF3E00',
  },
  {
    label: 'JavaScript',
    icon: 'javascript',
    value: 'js',
    color: 'F7DF1E',
  },
  {
    label: 'TypeScript',
    icon: 'typescript',
    value: 'ts',
    color: '3178C6',
  },
  {
    label: 'Vite',
    icon: 'vite',
    value: 'vite',
    color: '646CFF',
  },
  {
    label: 'Next.js',
    icon: 'nextdotjs',
    value: 'next-js',
    color: '000000',
  },
  {
    label: 'NextUI',
    icon: 'nextui',
    value: 'next-ui',
    color: '000000',
  },
  {
    label: 'Tailwind CSS',
    icon: 'tailwindcss',
    value: 'tailwindcss',
    color: '06B6D4',
  },
  {
    label: 'Ant Design',
    icon: 'antdesign',
    value: 'antd',
    color: '0170FE',
  },
  {
    label: 'React Router',
    icon: 'reactrouter',
    value: 'react-router',
    color: 'CA4245',
  },
  {
    label: 'Lucide',
    icon: 'lucide',
    value: 'lucide',
    color: 'F56565',
  },
  {
    label: 'HeadlessUI',
    icon: 'headlessui',
    value: 'headless-ui',
    color: '66E3FF',
  },
];
